package com.vonrobke.dna_sequence;

import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) {
	String dna = "GATTCAGAAACCAAAATTAATGTACCCACAAACAGACCCAAAACACCACCCCACTCAGACACAAACTCACCAAAACGGTCAAACTTGACATAAACAGCAAAACCACCCTGTAACCCTACCACCCTAGCAAGAACAAGTAACGACACCCGCAATCACCAGCCACAATCCAGGAAAAAGCGCAACCCCCTAGGAACCCAAACAATCACAAAAACCAAAGAGCATAGGCAAAACAACCACACACCGCTGAACACAAGACCACACATGAAAAAACAAAAACCCATTAAGCCACCAAAAACAAGACACACCAACACCCTGCAAATATAACCCAAAACCGATAACCCACTAACATCAGATACAACACACCATAAGTAAAATAAAAAACACTAAGCCGTCAGAAAACGTCACAAACCCCAACAAAGAGGGCTTAATCCTAAAACCTCACACATCGGCAAAAAGCAGAAACCAGCTCACAAAAAAACCCCCCACTCGCCCACAAACAAACATACCAAAACCGTTCTACCTACACTTCAGCAGACCAAGAAATACCAAAAACAATACCAACAAACCGCATATCGAACCATAACACAACCACCCAACCAATAAACAGACCCACATCCCTCAGCAATCGAAAAAATACACAGGTCCATATATAAACCTCTCCAACCACAACAAAATATAAAATAAGAAGCAAAACACATAACTACTGCCAAAACAAACCCCAACCCATGGCCAAAAAACACTAAGAACAAAAACTCAGGAACAAACCCCCAACCCAGCACAAACCCCCAAAACGAACAAAACAAGATCTCTAAAACACAGACCCGCCCAAAACAAAAAACCCAGCTAAATGACTAGCGCAAACAGCAACACAACCAACCCCACACCCGTTTTTATCAACGCACCAACACAAAACCAGCATCAAAACAAATCACAAAGTCGCCACAACGACCACAACAAACGCAACCCCCGAAAACATAGATAGGAAATCCCAACCCCCACC";
	RepeatedDnaSequence dnaSeq = new RepeatedDnaSequence();

	List<String> repeatedDnaSequences = new ArrayList<>(dnaSeq.findRepeatedDnaSequences(dna));

        for (String sequence :
                repeatedDnaSequences) {
            System.out.println(sequence);
        }
    }
}
